name: dascore
channels:
  - conda-forge
dependencies:
  - pytest
  - pydantic>2.0
  - pip
  - pandas
  - pooch>=1.2
  - xarray
  - pre-commit
  - pytables
  - h5py
  - matplotlib
  - scipy>=1.10.0
  - findiff
  - jupyter
  - nbformat
  - tk  # needed for plotting
