project:
  type: website
  output-dir: _site

filters:
  - filters/fill_links.py

format:
  html:
    toc: true
    theme:
      light: yeti
    code-copy: true
    code-overflow: wrap
    css: styles.css

website:
  title: "DASCore"
  repo-url: https://github.com/dasdae/dascore
  site-path: /docs

  image: "_static/logo.png"
  favicon: "_static/logo.png"
  twitter-card: true
  repo-subdir: docs
  repo-branch: master
  repo-actions: [edit]
  page-navigation: true

  navbar:
    logo: _static/logo.png
    logo-alt: "DASCore logo."
    background: light
    search: true
    left:
      - text: Introduction
        file: index.qmd

      - text: Tutorial
        file: tutorial/concepts.qmd

      - text: Recipes
        file: recipes/overview.qmd

      - text: Contributing
        file: contributing/contributing.qmd

      - text: API
        file: api/dascore.qmd

    right:

      - icon: twitter
        href: https://twitter.com/dasdae_org
        aria-label: DASDAE Twitter

      - icon: github
        href: https://github.com/dasdae/dascore
        aria-label: DASCore GitHub

  sidebar:
    - title: "About"
      style: "floating"
      collapse-level: 2
      logo: "_static/logo.png"
      search: true
      contents:
        - text: Introduction
          href: index.qmd

        - text: Changelog
          href: changelog.md

        - text: Contributors
          href: contributors.md

        - text: Acknowledgements
          href: acknowledgements.md

    - title: "Tutorial"
      contents:
        - text: DASCore Concepts
          href: tutorial/concepts.qmd

        - text: Patch
          href: tutorial/patch.qmd

        - text: Spool
          href: tutorial/spool.qmd

        - text: Processing
          href: tutorial/processing.qmd

        - text: Visualization
          href: tutorial/visualization.qmd

        - text: File IO
          href: tutorial/file_io.qmd

    - title: 'Recipes'
      contents:
        - recipes/overview.qmd

        - text: How to Contribute?
          href: recipes/how_to_contribute.qmd

        - text: Contributing to Documentation
          href: recipes/contributing_to_documentation.qmd

    - title: "Contributing"
      contents:
        - contributing/contributing.qmd

        - text: Dev Install
          href: contributing/dev_install.qmd

        - text: Style
          href: contributing/style_and_linting.qmd

        - text: "Testing"
          href: contributing/testing.qmd

        - text: "Adding Test Data"
          href: contributing/adding_test_data.qmd

        - text: Documentation
          href: contributing/documentation.qmd

        - text: General Guidelines
          href: contributing/general_guidelines.qmd

        - text: "Adding a new format"
          href: contributing/new_format.qmd

        - text: "Code of Conduct"
          href: contributing/code_of_conduct.qmd

    - title: 'API'
      contents:
        - auto: "api"


bibliography: references.bib
